name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: vnpaydb
          MYSQL_USER: giakhanh
          MYSQL_PASSWORD: giakhanh123
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h "localhost" --silent; do
            echo 'waiting for mysql to be ready...'
            sleep 5
          done
      - name: Build with Maven
        run: mvn clean install