name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: mvn -f pom.xml clean test -e -X
        env:
          DB_URL: jdbc:mysql://localhost:3306/vnpaydb
          DB_USERNAME: giakhanh
          DB_PASSWORD: giakhanh123

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
        env:
          DB_URL: jdbc:mysql://localhost:3306/vnpaydb
          DB_USERNAME: giakhanh
          DB_PASSWORD: giakhanh123
